### ISSUE TITLE
Prepare migration tests in CI

### ISSUE THREAD

**Issue by m-trojanowski** [magma/domain-proxy#212] opened 2021-11-15 10:09 UTC
As stated, we need checks for migrations in databases.

**Comment by xbend** [comment] 2022-01-10 12:08
In the past, we saw that a change introduced to Domain Proxy required changes in the database (migration) but a migration code was not generated. Yet the CI tests of Domain Proxy passed.

**Comment by xbend** [comment] 2022-03-29 11:38
Duplicate of #331

**Closed** 2022-03-29 11:38 UTC
