### ISSUE TITLE
Add orc8r integration tests to CI and improve make files

### ISSUE THREAD

**Issue by jkmar** [magma/domain-proxy#281] opened 2022-01-19 15:20 UTC
Orc8r tests should be included in CI.
Also integration tests are into 2 categories:
- orc8r - tests with orc8r, python command:
```python -m pytest -vvv -s -m orc8r --junit-xml=/backend/test_runner/test-results/test_report.xml tests```
- local - tests without orc8r, python commnand:
```python -m pytest -vvv -s -m local --junit-xml=/backend/test_runner/test-results/test_report.xml tests```
There should also be option to just deploy test environment without running tests (running test-runner with sleep infinity).

**Comment by xbend** [comment] 2022-01-28 12:57
Duplicate of #272

**Closed** 2022-01-28 12:58 UTC
